<a href="https://colab.research.google.com/github/neigit485/Challeng-_TelecomX_BR_Evasao_Clientes/blob/main/Challeng_TelecomX_BR_ETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import requests
import json

In [2]:
url = "https://raw.githubusercontent.com/ingridcristh/challenge2-data-science/main/TelecomX_Data.json"

In [3]:
response = requests.get(url)
data_json = response.json()

In [4]:
df_telecom = pd.json_normalize(data_json)

In [5]:
print("Dados carregados com sucesso!")
display(df_telecom.head())

Dados carregados com sucesso!

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [6]:
df_telecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [7]:
display(df_telecom.describe())

       customer.SeniorCitizen  customer.tenure  account.Charges.Monthly
count             7267.000000      7267.000000              7267.000000
mean                 0.162653        32.346498                64.720098
std                  0.369074        24.571773                30.129572
min                  0.000000         0.000000                18.250000
25%                  0.000000         9.000000                35.425000
50%                  0.000000        29.000000                70.300000
75%                  0.000000        55.000000                89.875000
max                  1.000000        72.000000               118.750000

In [8]:
print("\nColunas do Dataset:")
print(df_telecom.columns.tolist())

Colunas do Dataset:
['customerID', 'Churn', 'customer.gender', 'customer.SeniorCitizen', 'customer.Partner', 'customer.Dependents', 'customer.tenure', 'phone.PhoneService', 'phone.MultipleLines', 'internet.InternetService', 'internet.OnlineSecurity', 'internet.OnlineBackup', 'internet.DeviceProtection', 'internet.TechSupport', 'internet.StreamingTV', 'internet.StreamingMovies', 'account.Contract', 'account.PaperlessBilling', 'account.PaymentMethod', 'account.Charges.Monthly', 'account.Charges.Total']

In [9]:
# Converter 'Total' para numérico, forçando erros a virarem NaN (vazio)
df_telecom['account.Charges.Total'] = pd.to_numeric(df_telecom['account.Charges.Total'], errors='coerce')
print(df_telecom['account.Charges.Total'].dtypes)

float64

In [10]:
colunas_texto = df_telecom.select_dtypes(include=['object']).columns

for col in colunas_texto:
    df_telecom[col] = df_telecom[col].str.strip()

In [11]:
df_telecom['account.Charges.Total'] = pd.to_numeric(df_telecom['account.Charges.Total'], errors='coerce')

In [12]:
df_telecom['account.Charges.Total'] = df_telecom['account.Charges.Total'].fillna(0.0)

In [13]:
print(f"Linhas com Churn vazio antes da remoção: {df_telecom[df_telecom['Churn'] == ''].shape[0]}")

Linhas com Churn vazio antes da remoção: 224

In [14]:
df_telecom = df_telecom[df_telecom['Churn'] != '']

In [15]:
df_telecom.reset_index(drop=True, inplace=True)

In [16]:
print("\n--- Informações após Tratamento ---")
df_telecom.info()

--- Informações após Tratamento ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7043 non-null   object
 1   Churn                      7043 non-null   object
 2   customer.gender            7043 non-null   object
 3   customer.SeniorCitizen     7043 non-null   int64
 4   customer.Partner           7043 non-null   object
 5   customer.Dependents        7043 non-null   object
 6   customer.tenure            7043 non-null   int64
 7   phone.PhoneService         7043 non-null   object
 8   phone.MultipleLines        7043 non-null   object
 9   internet.InternetService   7043 non-null   object
 10  internet.OnlineSecurity    7043 non-null   object
 11  internet.OnlineBackup      7043 non-null   object
 12  internet.DeviceProtection  7043 non-null   object
 13  internet.TechSupport       7043 non-null   object
 14  internet.StreamingTV       7043 non-null   object
 15  internet.StreamingMovies   7043 non-null   object
 16  account.Contract           7043 non-null   object
 17  account.PaperlessBilling   7043 non-null   object
 18  account.PaymentMethod      7043 non-null   object
 19  account.Charges.Monthly    7043 non-null   float64
 20  account.Charges.Total      7043 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [17]:
print("\n--- Estatísticas de TotalCharges (agora numérico) ---")
display(df_telecom['account.Charges.Total'].describe())

--- Estatísticas de TotalCharges (agora numérico) ---

count    7043.000000
mean     2279.734304
std      2266.794470
min         0.000000
25%       398.550000
50%      1394.550000
75%      3786.600000
max      8684.800000
Name: account.Charges.Total, dtype: float64

In [18]:
# Verificar se sobrou algum Churn vazio
print(f"\nLinhas com Churn vazio após remoção: {df_telecom[df_telecom['Churn'] == ''].shape[0]}")

Linhas com Churn vazio após remoção: 0

In [19]:
df_telecom['Contas_Diarias'] = round(df_telecom['account.Charges.Monthly'] / 30, 2)

In [20]:
print("Amostra das novas colunas:")
display(df_telecom[['account.Charges.Monthly', 'Contas_Diarias']].head())

Amostra das novas colunas:

   account.Charges.Monthly  Contas_Diarias
0                     65.6            2.19
1                     59.9            2.00
2                     73.9            2.46
3                     98.0            3.27
4                     83.9            2.80

In [21]:
print("\nEstatísticas do Gasto Diário:")
display(df_telecom['Contas_Diarias'].describe())

Estatísticas do Gasto Diário:

count    7043.000000
mean        2.158675
std         1.003088
min         0.610000
25%         1.180000
50%         2.340000
75%         2.990000
max         3.960000
Name: Contas_Diarias, dtype: float64

In [22]:
col_translation = {
    'customerID': 'ID_Cliente',
    'Churn': 'Churn',
    'customer.gender': 'Genero',
    'customer.SeniorCitizen': 'Idoso',
    'customer.Partner': 'Parceiro',
    'customer.Dependents': 'Dependentes',
    'customer.tenure': 'Meses_Contrato',
    'phone.PhoneService': 'Servico_Telefonico',
    'phone.MultipleLines': 'Multiplas_Linhas',
    'internet.InternetService': 'Servico_Internet',
    'internet.OnlineSecurity': 'Seguranca_Online',
    'internet.OnlineBackup': 'Backup_Online',
    'internet.DeviceProtection': 'Protecao_Dispositivo',
    'internet.TechSupport': 'Suporte_Tecnico',
    'internet.StreamingTV': 'Streaming_TV',
    'internet.StreamingMovies': 'Streaming_Filmes',
    'account.Contract': 'Contrato',
    'account.PaperlessBilling': 'Fatura_Digital',
    'account.PaymentMethod': 'Metodo_Pagamento',
    'account.Charges.Monthly': 'Cobranca_Mensal',
    'account.Charges.Total': 'Cobranca_Total',
    'Contas_Diarias': 'Cobranca_Diaria'  # Padronizando o nome da coluna criada anteriormente
}

In [23]:
col_translation = {
    'customerID': 'ID_Cliente',
    'Churn': 'Churn',
    'customer.gender': 'Genero',
    'customer.SeniorCitizen': 'Idoso',
    'customer.Partner': 'Parceiro',
    'customer.Dependents': 'Dependentes',
    'customer.tenure': 'Meses_Contrato',
    'phone.PhoneService': 'Servico_Telefonico',
    'phone.MultipleLines': 'Multiplas_Linhas',
    'internet.InternetService': 'Servico_Internet',
    'internet.OnlineSecurity': 'Seguranca_Online',
    'internet.OnlineBackup': 'Backup_Online',
    'internet.DeviceProtection': 'Protecao_Dispositivo',
    'internet.TechSupport': 'Suporte_Tecnico',
    'internet.StreamingTV': 'Streaming_TV',
    'internet.StreamingMovies': 'Streaming_Filmes',
    'account.Contract': 'Contrato',
    'account.PaperlessBilling': 'Fatura_Digital',
    'account.PaymentMethod': 'Metodo_Pagamento',
    'account.Charges.Monthly': 'Cobranca_Mensal',
    'account.Charges.Total': 'Cobranca_Total',
    'Contas_Diarias': 'Cobranca_Diaria'
}

In [24]:
val_translation = {
    'Yes': 'Sim',
    'No': 'Não',
    'No internet service': 'Sem serviço de internet',
    'No phone service': 'Sem serviço telefônico',
    'Male': 'Masculino',
    'Female': 'Feminino',
    'DSL': 'DSL',
    'Fiber optic': 'Fibra ótica',
    'Month-to-month': 'Mensal',
    'One year': 'Um ano',
    'Two year': 'Dois anos',
    'Electronic check': 'Cheque eletrônico',
    'Mailed check': 'Cheque via correio',
    'Bank transfer (automatic)': 'Transferência bancária (automática)',
    'Credit card (automatic)': 'Cartão de crédito (automático)'
}

In [25]:
df_telecom.rename(columns=col_translation, inplace=True)

In [26]:
cols_to_translate = df_telecom.select_dtypes(include=['object']).columns.drop('ID_Cliente')
df_telecom[cols_to_translate] = df_telecom[cols_to_translate].replace(val_translation)

In [27]:
df_telecom['Churn'] = df_telecom['Churn'].replace({'Sim': 1, 'Não': 0})

/tmp/ipython-input-2921245145.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_telecom['Churn'] = df_telecom['Churn'].replace({'Sim': 1, 'Não': 0})

In [28]:
print("Amostra dos dados padronizados:")
display(df_telecom.head())

Amostra dos dados padronizados:

,ID_Cliente,Churn,Genero,Idoso,Parceiro,Dependentes,Meses_Contrato,Servico_Telefonico,Multiplas_Linhas,Servico_Internet,...,Protecao_Dispositivo,Suporte_Tecnico,Streaming_TV,Streaming_Filmes,Contrato,Fatura_Digital,Metodo_Pagamento,Cobranca_Mensal,Cobranca_Total,Cobranca_Diaria
0,0002-ORFBO,0,Feminino,0,Sim,Sim,9,Sim,Não,DSL,...,Não,Sim,Sim,Não,Um ano,Sim,Cheque via correio,65.6,593.30,2.19
1,0003-MKNFE,0,Masculino,0,Não,Não,9,Sim,Sim,DSL,...,Não,Não,Não,Sim,Mensal,Não,Cheque via correio,59.9,542.40,2.00
2,0004-TLHLJ,1,Masculino,0,Não,Não,4,Sim,Não,Fibra ótica,...,Sim,Não,Não,Não,Mensal,Sim,Cheque eletrônico,73.9,280.85,2.46
3,0011-IGKFF,1,Masculino,1,Sim,Não,13,Sim,Não,Fibra ótica,...,Sim,Não,Sim,Sim,Mensal,Sim,Cheque eletrônico,98.0,1237.85,3.27
4,0013-EXCHZ,1,Feminino,1,Sim,Não,3,Sim,Não,Fibra ótica,...,Não,Sim,Sim,Não,Mensal,Sim,Cheque via correio,83.9,267.40,2.80

In [29]:
print("\nInformações das Colunas (Note que Churn agora é int64):")
df_telecom.info()

Informações das Colunas (Note que Churn agora é int64):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID_Cliente            7043 non-null   object
 1   Churn                 7043 non-null   int64
 2   Genero                7043 non-null   object
 3   Idoso                 7043 non-null   int64
 4   Parceiro              7043 non-null   object
 5   Dependentes           7043 non-null   object
 6   Meses_Contrato        7043 non-null   int64
 7   Servico_Telefonico    7043 non-null   object
 8   Multiplas_Linhas      7043 non-null   object
 9   Servico_Internet      7043 non-null   object
 10  Seguranca_Online      7043 non-null   object
 11  Backup_Online         7043 non-null   object
 12  Protecao_Dispositivo  7043 non-null   object
 13  Suporte_Tecnico       7043 non-null   object
 14  Streaming_TV          7043 non-null   object
 15  Streaming_Filmes      7043 non-null   object
 16  Contrato              7043 non-null   object
 17  Fatura_Digital        7043 non-null   object
 18  Metodo_Pagamento      7043 non-null   object
 19  Cobranca_Mensal       7043 non-null   float64
 20  Cobranca_Total        7043 non-null   float64
 21  Cobranca_Diaria       7043 non-null   float64
dtypes: float64(3), int64(3), object(16)
memory usage: 1.2+ MB

In [30]:
(df_telecom['Churn'].mean())

np.float64(0.2653698707936959)

In [34]:
display(df_telecom.describe().round(2).T)

,count,mean,std,min,25%,50%,75%,max
Churn,7043.0,0.27,0.44,0.00,0.00,0.00,1.00,1.00
Idoso,7043.0,0.16,0.37,0.00,0.00,0.00,0.00,1.00
Meses_Contrato,7043.0,32.37,24.56,0.00,9.00,29.00,55.00,72.00
Cobranca_Mensal,7043.0,64.76,30.09,18.25,35.50,70.35,89.85,118.75
Cobranca_Total,7043.0,2279.73,2266.79,0.00,398.55,1394.55,3786.60,8684.80
Cobranca_Diaria,7043.0,2.16,1.00,0.61,1.18,2.34,2.99,3.96

In [35]:
display(df_telecom.describe(include=['object']).T)

                     count unique                top  freq
ID_Cliente            7043   7043         9995-HOTOH     1
Genero                7043      2          Masculino  3555
Parceiro              7043      2                Não  3641
Dependentes           7043      2                Não  4933
Servico_Telefonico    7043      2                Sim  6361
Multiplas_Linhas      7043      3                Não  3390
Servico_Internet      7043      3        Fibra ótica  3096
Seguranca_Online      7043      3                Não  3498
Backup_Online         7043      3                Não  3088
Protecao_Dispositivo  7043      3                Não  3095
Suporte_Tecnico       7043      3                Não  3473
Streaming_TV          7043      3                Não  2810
Streaming_Filmes      7043      3                Não  2785
Contrato              7043      3             Mensal  3875
Fatura_Digital        7043      2                Sim  4171
Metodo_Pagamento      7043      4  Cheque eletrônico  2365

In [37]:
taxa_churn = df_telecom['Churn'].mean() * 100
print(f"\n Taxa Geral de Cancelamento (Churn): {taxa_churn:.2f}%")

 Taxa Geral de Cancelamento (Churn): 26.54%